### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by LuffyLouis** [broadinstitute/tensorqtl#109]
When I ran the tensorqtl, this error was throwed and meanwhile, I found the GPU memory usage reached almost 100% (GPU: RTX3090Ti). So is this a problem of insufficient gpu memory?
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions
The traceback as follows:
processing phenotype 1009/1943Traceback (most recent call last):
  File "/home/luffy/miniconda3/envs/eqtl/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/luffy/miniconda3/envs/eqtl/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/luffy/miniconda3/envs/eqtl/lib/python3.9/site-packages/tensorqtl/__main__.py", line 2, in <module>
    tensorqtl.main()
  File "/home/luffy/miniconda3/envs/eqtl/lib/python3.9/site-packages/tensorqtl/tensorqtl.py", line 142, in main
    res_df = cis.map_cis(genotype_df, variant_df, phenotype_df, phenotype_pos_df, covariates_df=covariates_df,
  File "/home/luffy/miniconda3/envs/eqtl/lib/python3.9/site-packages/tensorqtl/cis.py", line 716, in map_cis
    res = calculate_cis_permutations(genotypes_t, phenotype_t, permutation_ix_t,
  File "/home/luffy/miniconda3/envs/eqtl/lib/python3.9/site-packages/tensorqtl/cis.py", line 56, in calculate_cis_permutations
    corr_t = calculate_corr(genotypes_t, permutations_t, residualizer=residualizer).pow(2)  # genotypes x permutations
  File "/home/luffy/miniconda3/envs/eqtl/lib/python3.9/site-packages/tensorqtl/core.py", line 152, in calculate_corr
    return torch.mm(genotype_res_t, phenotype_res_t.t())

**Comment by LuffyLouis** [comment]
The sample size is 64, and number of variants is 9350k. This error only happened for cis mode, so is it the issue of permutation test?

**Comment by francois-a** [comment]
Permutations will require more memory, so that's potentially the problem. Can you check if lowering the number with `--permutations` fixes the issue?
