### ISSUE TITLE
Memory Allocation Issue during trans-QTL Mapping 

### ISSUE THREAD

**Issue by wangyf1125** [broadinstitute/tensorqtl#124]
Hi, thanks for developing and maintaining such an excellent tool.
I’m currently experiencing a memory allocation issue while running trans-QTL mapping with a significant dataset. Despite allocating 300GB of memory (`--mem 300G`), the process fails with `numpy.core._exceptions._ArrayMemoryError`
Here are the specifics of my task:

```
Warning: 'rfunc' cannot be imported. R and the 'rpy2' Python package are needed.
trans-QTL mapping
  * 419 samples
  * 13424 phenotypes
  * 44 covariates
  * 83236 variants
    processing batch 2/2
    elapsed time: 3.22 min
  * 83096 variants passed MAF >= 0.01 filtering
```

```
Mapping files: 100%|██████████| 3/3 [00:00<00:00, 15.02it/s]
Traceback (most recent call last):
 File "/mnt/vast/hpc/homes/yw4257/tmpvnc0a637/singularity_run_36600.py", line 58, in <module>
  trans_df = trans.map_trans(genotype_df, 
 File "/opt/conda/envs/TensorQTL/lib/python3.10/site-packages/tensorqtl/trans.py", line 159, in map_trans
  res = np.concatenate(res)
 File "<__array_function__ internals>", line 200, in concatenate
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 58.2 GiB for an array with shape (1115480704, 7) and data type object
```

Given the scale of the data and the memory allocation, I was anticipating smooth execution.

Could you help me with this, thanks!!

**Comment by gaow** [comment]
Although in principle it is possible to break down the genotype by chroms to easy the memory usage, it would not be feasible to do permutation testing properly (which is a tremendous task anyways if there are many variants involved). Currently we stick to per chrom analysis without relying on multiple testing results.

**Comment by francois-a** [comment]
It looks like you're generating dense output — are you changing the default `pval_threshold`? If you want that you should use `--return_dense` instead. For permutations/FDR, you don't need the dense output though. Can you specify what you're trying to do?

**Comment by gaow** [comment]
Thank you @francois-a -- we set `pval_threshold` by setting it to as high as 1.0 because we would like to have some association results under the null which is an input to a trans-QTL integration step downstreams. The core `tensorQTL` calls in our [trans analysis pipeline](https://cumc.github.io/xqtl-pipeline/code/association_scan/TensorQTL/TensorQTL.html#transqtl-association-testing) looks like this where by default in our pipeline `pval_threshold = 1.0`  :

```python

    ## Trans analysis
    trans_df = trans.map_trans(genotype_df, 
                            phenotype_df,
                            covariates_df, 
                            batch_size=$[batch_size],
                            return_sparse=True, 
                            return_r2 = True, 
                            pval_threshold=$[pval_threshold], 
                            maf_threshold=$[maf_threshold])

    ## Filter out cis signal, again if customized cis windows are used, the windows is [start-win,end + win] where win = 0, else it is [start - win, start + win]
    trans_df = trans.filter_cis(trans_df, phenotype_pos_df, variant_df, window=window)   

    ## Permutation

    if $['True' if permutation else 'False']:
        perm_df = trans.map_permutations(genotype_df, covariates_df, batch_size=$[batch_size],
                             maf_threshold=$[maf_threshold])
        perm_output = trans.apply_permutations(perm_df,trans_df)
        perm_output.to_csv("$[_output:nn].transqtl_permutation.gz", sep='\t',index = None, compression={'method': 'gzip', 'compresslevel': 9})
```

That is why we put `return_dense = True`.

I guess from your suggestion, we can do two rounds of analysis:

1. Per-chrom analysis, or breaking genotypes into even smaller chunks than chroms, where we report all results (regardless of p-value) and skip permutation testing
2. We then focus on permutation testing, setting p-value cutoff to some small numbers and use sparse matrix to save marginal association results.

Do you think it is the correct approach to take? 

On the other hand, let me think into the downstreams trans-QTL association analysis methods to see if we can get away without using those summary statistics corresponding to large p-values. Then we may be able to get away with a smaller p-value cutoff here.
