### ISSUE TITLE
map_trans fails with int error

### ISSUE THREAD

**Issue by JonMarten** [broadinstitute/tensorqtl#13]
I have been running tensorQTL on single phenotypes but encounter the following error:

```
>>> gw_trans_df = trans.map_trans(gw_genotype_df, phenotype_df, covariates_df, return_sparse=True, maf_threshold = 0.03)
trans-QTL mapping
  * 4038 samples
  * 1 phenotypes
  * 25 covariates
  * 162168 variants
    processing batch 3/9Traceback (most recent call last):
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/numpy/lib/index_tricks.py", line 376, in __getitem__
    axis = int(item)
ValueError: invalid literal for int() with base 10: 'rs202244392'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/tensorqtl/trans.py", line 115, in map_trans
    res.append(np.c_[variant_ids[ix[:,0]], phenotype_df.index[ix[:,1]], tstat.cpu(), maf[ix[:,0]]])
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/numpy/lib/index_tricks.py", line 379, in __getitem__
    raise ValueError("unknown special directive")
ValueError: unknown special directive
    processing batch 8/9

```

Looking at the genotype_df for this variant, it seems to be to be the right kind of value:
```
 gw_genotype_df.loc["rs202244392"]
iid
110000315494    2
110000366469    2
110000399461   -1
110000399523    2
110000399542    2
               ..
119999967049    2
119999967065    2
119999984952    2
119999984992    2
119999995956    2
Name: rs202244392, Length: 4144, dtype: int8


>>> gw_genotype_df.loc["rs202244392"].value_counts()
 2    3048
-1     636
 1     448
 0      12
Name: rs202244392, dtype: int64
```

Do you have any idea what might be going wrong here? I know the primary purpose of tensorQTL isn't single-phenotype analyses but I've been able to run this with different genotype files before.

**Comment by francois-a** [comment]
Hi,
Analyses with single phenotypes should definitely work. I can't figure out the issue from the error message. Would you be able to share the SNP-phenotype pair (or some other minimal example) that reproduces the error?

**Comment by JonMarten** [comment]
Sorry for the long delay here. While trying to create an anonymised data set to share, I found that setting `return_sparse = False` let the function run to completion on the SNP-phenotype pair that was initially causing problems. 

However, when running on all SNPs, I get a new error:
```
>>> gw_trans_df = trans.map_trans(gw_genotype_df, phenotype_df, covariates_df, return_sparse=False)
trans-QTL mapping
  * 4038 samples
  * 1 phenotypes
  * 25 covariates
  * 162138 variants
    processing batch 9/9
    elapsed time: 0.17 min
Traceback (most recent call last):
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1681, in create_block_manager_from_blocks
    mgr = BlockManager(blocks, axes)
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 143, in __init__
    self._verify_integrity()
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 345, in _verify_integrity
    construction_error(tot_items, block.shape[1:], self.axes)
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1719, in construction_error
    "Shape of passed values is {0}, indices imply {1}".format(passed, implied)
ValueError: Shape of passed values is (113212, 1), indices imply (1403, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/tensorqtl/trans.py", line 140, in map_trans
    pval_df = pd.DataFrame(pval, index=variant_ids, columns=phenotype_df.index)
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/pandas/core/frame.py", line 440, in __init__
    mgr = init_ndarray(data, index, columns, dtype=dtype, copy=copy)
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 213, in init_ndarray
    return create_block_manager_from_blocks(block_values, [columns, index])
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1688, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/home/jm2294/.conda/envs/tensorQTL/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1719, in construction_error
    "Shape of passed values is {0}, indices imply {1}".format(passed, implied)
ValueError: Shape of passed values is (113212, 1), indices imply (1403, 1)
```

Does this make any sense to you?

**Comment by JonMarten** [comment]
If it helps, the SNP-phenotype pair that worked with `bad_trans_df = trans.map_trans(bad_snps,  bad_phe, bad_cov, return_sparse=False)` produced the following:
```
>>> bad_trans_df
ID                badphe
variant_id
badsnp      4.824622e-07
```

Having not tried to run trans.map_trans quite like this before, I'm not actually sure what `4.824622e-07` corresponds to - a p-value of association?

**Comment by francois-a** [comment]
Hi,
Can you please post example data that reproduces this error?

**Comment by francois-a** [comment]
Empty batches should not be a problem, at least with the configurations I tested.

Can you reproduce the error with scrambled data, and if so could you share that?

The regression slope is now returned in trans mode, please see 1ba37bb876b9dddd26d58c3070431265ece42a8f.

**Comment by JonMarten** [comment]
This issue no longer occurs now I'm running on the whole dataset.
