### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by desindygogo** [broadinstitute/tensorqtl#130]
Hello, I encountered the following error when performing permutation, there is no output, but there it seems normal in the log file , I would like to know what is the cause of this?  
The same data works properly when using cis_nominal mode.

thanks!

----------------------------------
**ocessing phenotype 10391/10393^M    processing phenotype 10392/10393WARNING: scipy.optimize.newton failed to converge (running scipy.optimize.minimize)
^M    processing phenotype 10393/10393
Traceback (most recent call last):
  File "/share/home/zhuyunfei/miniconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/share/home/zhuyunfei/miniconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/share/home/zhuyunfei/miniconda3/lib/python3.9/site-packages/tensorqtl/__main__.py", line 2, in <module>
    tensorqtl.main()
  File "/share/home/zhuyunfei/miniconda3/lib/python3.9/site-packages/tensorqtl/tensorqtl.py", line 141, in main
    calculate_qvalues(res_df, fdr=args.fdr, qvalue_lambda=args.qvalue_lambda, logger=logger)
  File "/share/home/zhuyunfei/miniconda3/lib/python3.9/site-packages/tensorqtl/post.py", line 40, in calculate_qvalues
    r = stats.pearsonr(res_df['pval_perm'], res_df['pval_beta'])[0]
  File "/share/home/zhuyunfei/miniconda3/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 4455, in pearsonr
    normym = linalg.norm(ym)
  File "/share/home/zhuyunfei/miniconda3/lib/python3.9/site-packages/scipy/linalg/_misc.py", line 145, in norm
    a = np.asarray_chkfinite(a)
  File "/share/home/zhuyunfei/miniconda3/lib/python3.9/site-packages/numpy/lib/function_base.py", line 628, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
WARNING: scipy.optimize.newton failed to converge (running scipy.optimize.minimize)
  Time elapsed: 10.47 min
done.
  * writing output
Computing q-values
  * Number of phenotypes tested: 10393**
----------------------------------

**Comment by francois-a** [comment]
Please try this again with the latest commit.
