### ISSUE TITLE
Incompatible with pandas plink 2.2

### ISSUE THREAD

**Issue by liangyy** [broadinstitute/tensorqtl#30]
Hi @francois-a, thanks for developing this extremely useful tool. Recently we encountered the following error 

```
python3 -m [genotype_prefix] [bed_gz] [out_prefix] --mode trans
[Nov 17 09:14:45] Running TensorQTL: trans-QTL mapping
  * WARNING: using CPU!
  * reading phenotypes (/gpfs/data/im-lab/nas40t2/natasha/pheno-tensorqtl.bed.gz)
Mapping files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [02:01<00:00, 40.61s/it]
/gpfs/data/im-lab/nas40t2/bin/envs/tensorqtl/lib/python3.8/site-packages/tensorqtl/genotypeio.py:144: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]
To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  self.bed = self.bed[:,ix]
Traceback (most recent call last):
  File "/gpfs/data/im-lab/nas40t2/bin/envs/tensorqtl/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfs/data/im-lab/nas40t2/bin/envs/tensorqtl/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/gpfs/data/im-lab/nas40t2/bin/envs/tensorqtl/lib/python3.8/site-packages/tensorqtl/__main__.py", line 2, in <module>
    tensorqtl.main()
  File "/gpfs/data/im-lab/nas40t2/bin/envs/tensorqtl/lib/python3.8/site-packages/tensorqtl/tensorqtl.py", line 100, in main
    pr = genotypeio.PlinkReader(args.genotype_path, select_samples=phenotype_df.columns, dtype=np.int8)
  File "/gpfs/data/im-lab/nas40t2/bin/envs/tensorqtl/lib/python3.8/site-packages/tensorqtl/genotypeio.py", line 159, in __init__
    self.chrs = self.bim['chrom'].unique().tolist()
AttributeError: 'StringArray' object has no attribute 'tolist'
```

And here is the environment we used.
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
_pytorch_select           0.2                       gpu_0
_r-mutex                  1.0.0               anacondar_1
attrs                     20.3.0                   pypi_0    pypi
binutils_impl_linux-64    2.31.1               h6176602_1
binutils_linux-64         2.31.1               h6176602_9
blas                      1.0                         mkl
bwidget                   1.9.11                        1
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.10.14                    0
cairo                     1.14.12              h8948797_3
certifi                   2020.6.20          pyhd3eb1b0_3
cffi                      1.14.3                   pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0
cudnn                     7.6.5                cuda10.1_0
curl                      7.71.1               he644dc0_3    conda-forge
dask                      2.30.0                   pypi_0    pypi
deprecated                1.2.10                   pypi_0    pypi
fontconfig                2.13.0               h9420a91_0
freetype                  2.10.4               h5ab3b9f_0
fribidi                   1.0.10               h7b6447c_0
fsspec                    0.8.4                    pypi_0    pypi
gcc_impl_linux-64         7.3.0                habb00fd_1
gcc_linux-64              7.3.0                h553295d_9
gettext                   0.19.8.1             hd7bead4_3
gfortran_impl_linux-64    7.3.0                hdf63c60_1
gfortran_linux-64         7.3.0                h553295d_9
glib                      2.66.2               h58526e2_0    conda-forge
graphite2                 1.3.14               h23475e2_0
gsl                       2.4                  h14c3975_4
gxx_impl_linux-64         7.3.0                hdf63c60_1
gxx_linux-64              7.3.0                h553295d_9
harfbuzz                  2.4.0                hca77d97_1
icu                       58.2                 he6710b0_3
iniconfig                 1.1.1                    pypi_0    pypi
jinja2                    2.11.2                     py_0
jpeg                      9b                   h024ee3a_2
krb5                      1.17.1               h173b8e3_0
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libcurl                   7.71.1               hcdd3856_3    conda-forge
libedit                   3.1.20191231         h46ee950_2    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libglib                   2.66.2               hbe7bbb4_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libpng                    1.6.37               hbc83047_0
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                h2733197_1
libuuid                   1.0.3                h1bed415_2
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               hb55368b_3
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
locket                    0.2.0                    pypi_0    pypi
lz4-c                     1.9.2                heb0550a_3
make                      4.2.1                h1bed415_1
markupsafe                1.1.1            py38h7b6447c_0
mkl                       2019.5                      281    conda-forge
mkl-service               2.3.0            py38he904b0f_0
mkl_fft                   1.2.0            py38h23d657b_0
mkl_random                1.1.0            py38h962f231_0
ncurses                   6.1               hf484d3e_1002    conda-forge
ninja                     1.10.0               hc9558a2_0    conda-forge
numpy                     1.19.2           py38h54aff64_0
numpy-base                1.19.2           py38hfa32c7d_0
openssl                   1.1.1h               h7b6447c_0
packaging                 20.4                     pypi_0    pypi
pandas                    1.1.4                    pypi_0    pypi
pandas-plink              2.2.2                    pypi_0    pypi
pango                     1.45.3               hd140c19_0
partd                     1.1.0                    pypi_0    pypi
pcre                      8.44                 he6710b0_0
pip                       20.0.2                     py_2    conda-forge
pixman                    0.40.0               h7b6447c_0
pluggy                    0.13.1                   pypi_0    pypi
py                        1.9.0                    pypi_0    pypi
pyarrow                   2.0.0                    pypi_0    pypi
pycparser                 2.20                       py_0    conda-forge
pyparsing                 2.4.7                    pypi_0    pypi
pytest                    6.1.2                    pypi_0    pypi
python                    3.8.0                h357f687_5    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.4.0           cuda101py38h02f0884_0
pytz                      2020.4                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
r-base                    3.6.1                haffb61f_2
readline                  8.0                  hf8c457e_0    conda-forge
rpy2                      3.3.6           py38r36hab2c0dc_0    conda-forge
scipy                     1.5.4                    pypi_0    pypi
setuptools                50.3.1           py38h06a4308_1
simplegeneric             0.8.1                    py38_2
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tensorqtl                 1.0.4                    pypi_0    pypi
tk                        8.6.10               hed695b0_0    conda-forge
tktable                   2.10                 h14c3975_0
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
tqdm                      4.51.0                   pypi_0    pypi
tzlocal                   2.1                      py38_0
wheel                     0.34.2                     py_1    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
xarray                    0.16.1                   pypi_0    pypi
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstandard                 0.14.0                   pypi_0    pypi
zstd                      1.4.5                h9ceee32_0
```

With some look into the code, it seems that the error is due to the incompatibility with `pandas-plink=2.2` ([about loading BIM file](https://github.com/limix/pandas-plink/blob/ceefd1b957674c17c410c8cf92705adbf8eaf482/pandas_plink/_read.py#L306)). We were wondering if this issue will be fixed in the future or we should stick with an older version of `pandas-plink` in order to run tensorqtl. 

Thanks!

**Comment by francois-a** [comment]
Hi @liangyy, the latest commit actually fixes this. I'm checking a few more things but will release v1.0.5 later today.

**Comment by liangyy** [comment]
Hi @francois-a, thank you very much! We have a follow-up question on loading genotype file. We got the warning:
```
softwares/tensorqtl/tensorqtl/genotypeio.py:146: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  self.bed = self.bed[:,ix]
```
, which may be due the fact that our phenotype and genotype do not have the same ordering of individuals.

What would you suggest to do with this warning?

Thanks!

**Comment by francois-a** [comment]
Based on my experience it's fine to ignore this. It doesn't noticeably impact performance.

**Comment by liangyy** [comment]
Got you, thanks! I will close this issue.
