### ISSUE TITLE
numpy float depreciation causing errors

### ISSUE THREAD

**Issue by kimlorenz** [broadinstitute/tensorqtl#99]
our cluster recently updated numpy and we now get this error when trying to run tensorqtl:

Traceback (most recent call last):
  File "/appl/python-3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/appl/python-3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/appl/python-3.8/lib/python3.8/site-packages/tensorqtl/__main__.py", line 2, in <module>
    tensorqtl.main()
  File "/appl/python-3.8/lib/python3.8/site-packages/tensorqtl/tensorqtl.py", line 109, in main
    pr = genotypeio.PlinkReader(args.genotype_path, select_samples=phenotype_df.columns, dtype=np.int8)
  File "/appl/python-3.8/lib/python3.8/site-packages/tensorqtl/genotypeio.py", line 142, in __init__
    self.bim, self.fam, self.bed = read_plink(plink_prefix_path, verbose=verbose)
  File "/appl/python-3.8/lib/python3.8/site-packages/pandas_plink/_read.py", line 101, in read_plink
    from dask.array import concatenate
  File "/appl/python-3.8/lib/python3.8/site-packages/dask/array/__init__.py", line 3, in <module>
    from .core import (
  File "/appl/python-3.8/lib/python3.8/site-packages/dask/array/core.py", line 28, in <module>
    from . import chunk
  File "/appl/python-3.8/lib/python3.8/site-packages/dask/array/chunk.py", line 7, in <module>
    from . import numpy_compat as npcompat
  File "/appl/python-3.8/lib/python3.8/site-packages/dask/array/numpy_compat.py", line 21, in <module>
    np.divide(0.4, 1, casting="unsafe", dtype=np.float),
  File "/appl/python-3.8/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by francois-a** [comment]
Hi, it looks like this error is from dask, not tensorQTL. If updating dask doesn't fix it, I recommend using PLINK2's pgen to store genotypes instead, which uses a different parser (pgenlib) — I recommend switching to this in general, since it's faster.
